chat/urls.py
# urls.py
from django.urls import path
from .views import ask_question, question_list, answer_question, edit_question, edit_answer, delete_question, staff_unanswered_questions

urlpatterns = [
    path('ask/', ask_question, name='ask_question'),
    path('questions/', question_list, name='question_list'),
    path('answer/<int:question_id>/', answer_question, name='answer_question'),
    path('edit/<int:question_id>/', edit_question, name='edit_question'),
    path('delete/<int:question_id>/', delete_question, name='delete_question'),
    path('edit_answer/<int:question_id>/', edit_answer, name='edit_answer'),
    path('staff/unanswered/', staff_unanswered_questions, name='staff_unanswered_questions'),
]

exammania/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("home/", include("main.urls")),
    path("chat/", include("chat.urls")),
    path("videos/", include("videos.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views



app_name = "main"

urlpatterns = [
    path("", views.index, name="index"),
    path("book-solution/", views.book_solution, name="book_solution"),
    path("chapter-list/<str:book_name>/", views.chapterlist, name="chapter_list"),
    path("exercise-list/<str:book_name>/<str:chapter_name>/", views.exerciselist, name="exercise_list"),
    path("exercise-solution/<str:book_name>/<str:chapter_name>/<str:exercise_name>/<int:question_no>", views.exercisesolution, name="exercise_solution"),
    path("exam-solution/<str:exam_name>/<int:year>/<int:question_no>/", views.exam_solution, name="exam_solution"),
    path("notes/<str:subject>/", views.notes, name="notes"),
    path("notes-detailes/<str:subject>/<str:topic>/<str:chapter>/", views.notes_details, name="notes_details"),
    path("working-rules/<str:subject>/", views.wrules, name="working_rules"),
    path("working-rules-detailes/<str:subject>/<str:topic>/<str:chapter>/", views.wrules_details, name="working_rules_details"),
    path('generate-test/<str:subject>/', views.generate_test, name='generate_test'),
    path('test/<str:subject>/<str:question_ids>/', views.test_page, name='test_page'),
    path('submit-test/',views.submit_test, name='submit_test'),
    path('review-test/', views.review_test, name="review_test"),
    path('feedback/', views.feedback, name="feedback"),
    
]

main/models.py
from django.db import models

# Create your models here.

class ExamQuestionOptions(models.Model):
    content= models.TextField(unique=True)
    def __str__(self):
        return self.content
    
    

class ExamQuestion(models.Model):
    DIFFICULTY_CHOICES = (
        ('easy', 'Easy'),
        ('medium', 'Medium'),
        ('hard', 'Hard'),
    )
    SUBJECT_CHOICES=(
        ('physics', 'Physics'),
        ('chemistry', 'Chemistry'),
        ('math', 'Math'),
    )
    body= models.TextField(unique=True)
    answer= models.TextField(default=None)
    options= models.ManyToManyField(ExamQuestionOptions, related_name="options")
    correct_options = models.ManyToManyField(ExamQuestionOptions, related_name="correct_options")
    subject= models.CharField(max_length=25, choices=SUBJECT_CHOICES, default='physics')
    difficulty_level= models.CharField(max_length=20, choices=DIFFICULTY_CHOICES, default='medium')

    def __str__(self):
        return self.body
    
class Exam(models.Model):
    
    name= models.CharField(max_length=25)
    year= models.IntegerField()
    questions = models.ManyToManyField(ExamQuestion, related_name='Exams', blank=True, through="ExamQuestionIntermidiate")
    def __str__(self):
        return f"{self.name}-{self.year}"
    class Meta:
        ordering = ['name', 'year']


class ExamQuestionIntermidiate(models.Model):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    question = models.ForeignKey(ExamQuestion, on_delete=models.CASCADE)
    question_order = models.PositiveIntegerField()

    class Meta:
        ordering = ["question_order"]

    def save(self, *args, **kwargs):
        if not self.pk:
            # Set the order based on the number of existing questions for the exercise
            self.question_order = self.exam.questions.count() + 1
        super().save(*args, **kwargs)



class BookQuestionOption(models.Model):
    content= models.TextField(unique=True)
    def __str__(self):
        return self.content   

class BookQuestion(models.Model):
    DIFFICULTY_CHOICES = (
        ('easy', 'Easy'),
        ('medium', 'Medium'),
        ('hard', 'Hard'),
    )
    
    body= models.TextField(unique=True)
    answer= models.TextField(default=None)
    options= models.ManyToManyField(BookQuestionOption, related_name="options")
    correct_options = models.ManyToManyField(BookQuestionOption, related_name="correct_options")
    difficulty_level= models.CharField(max_length=20, choices=DIFFICULTY_CHOICES, default='medium')

    def __str__(self):
        return self.body
    


class Book(models.Model):
    name= models.CharField(max_length=250)
    SUBJECT_CHOICES=(
        ('physics', 'Physics'),
        ('chemistry', 'Chemistry'),
        ('math', 'Math'),
    )
    subject= models.CharField(max_length=100, choices=SUBJECT_CHOICES)
    image= models.ImageField(upload_to="images/")

    def __str__(self):
        return self.name


class Chapter(models.Model):
    name= models.CharField(max_length=250)
    book= models.ForeignKey(Book, related_name="chapters", on_delete=models.CASCADE)
    def __str__(self):
        return self.name
    
class Exercise(models.Model):
    name= models.CharField(max_length=250)
    questions= models.ManyToManyField(BookQuestion, related_name="Exercises", blank=True, through="ExerciseQuestionIntermidiate")
    chapter= models.ForeignKey(Chapter, related_name="exercises", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class ExerciseQuestionIntermidiate(models.Model):
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    question = models.ForeignKey(BookQuestion, on_delete=models.CASCADE)
    question_order = models.PositiveIntegerField()

    class Meta:
        ordering = ["question_order"]

    def save(self, *args, **kwargs):
        if not self.pk:
            # Set the order based on the number of existing questions for the exercise
            self.question_order = self.exercise.questions.count() + 1
        super().save(*args, **kwargs)


class UserSubmittedBookAnswer(models.Model):
    answer = models.TextField()
    book = models.CharField(max_length=250)
    chapter = models.CharField(max_length=250)
    exercise = models.CharField(max_length=250)
    no= models.IntegerField()

class BookQuestionFeedback(models.Model):
    feedback = models.TextField()
    book = models.CharField(max_length=250)
    chapter = models.CharField(max_length=250)
    exercise = models.CharField(max_length=250)
    no= models.IntegerField()

    



    


    

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Exam, Book, Chapter, Exercise, ExamQuestion, UserSubmittedBookAnswer, BookQuestionFeedback
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest, HttpResponseNotAllowed, JsonResponse
from django.urls import reverse
from random import sample
from datetime import datetime
from django.contrib.auth.decorators import login_required
from users.models import UserProfile
from django.views.decorators.csrf import csrf_exempt
import json
from django.core import serializers


def index(request):
  return render(request, "main/index.html")
     


def book_solution(request):
  Maths_Book=Book.objects.filter(subject="math")
  Physics_Book= Book.objects.filter(subject="physics")
  Chem_Book = Book.objects.filter(subject="chemistry")
  print(Maths_Book)
  print(Physics_Book)
  print(Chem_Book)
  dic= {
    "Maths_Book":Maths_Book,
    "Physics_Book":Physics_Book,
    "Chem_Book": Chem_Book,
  }
  return render(request, "main/booklist.html", dic)

def chapterlist(request, book_name):
  book=Book.objects.get(name=book_name)
  chapters=Chapter.objects.filter(book=book)
  dic= {
    "Chapters":chapters,
    "book":book,
  }

  return render(request, "main/chapterlist.html", dic)

def exerciselist(request, book_name, chapter_name):
  book=Book.objects.get(name=book_name)
  chapter = Chapter.objects.get(book__name=book_name, name=chapter_name)
  exercises = Exercise.objects.filter(chapter=chapter)
  dic={
    "Exercises": exercises,
    "Chapter": chapter,
    "Book":book,
    "no":0
  }
  print(book.name)
  print(chapter.name)
  return render(request, "main/exerciselist.html", dic)

def exercisesolution(request, book_name, chapter_name, exercise_name, question_no):
    # Use get_object_or_404 to retrieve the specific book based on the provided book_name
    book = get_object_or_404(Book, name=book_name)
    

    # Use get_object_or_404 to retrieve the specific chapter for the given book
    chapter = get_object_or_404(Chapter, book=book, name=chapter_name)
    

    # Use get_object_or_404 to retrieve the specific exercise for the given chapter
    exercise = get_object_or_404(Exercise, chapter=chapter, name=exercise_name)
    questions = exercise.questions.all()
    total_count = exercise.questions.all().count()

    
    question= questions[question_no]
    no = question_no + 1
    
    
    
    
    

    context = {
        "Book": book,
        "Chapter": chapter,
        "Exercise": exercise,
        "body": question.body,
        "answer":question.answer,
        "options":question.options.all(),
        "correct_options":question.correct_options.all(),
        "level":question.difficulty_level,
        "no":no,
        "count": total_count
        
    }

    return render(request, "main/exercise.html", context)
  
  

def exam_solution(request, exam_name, year, question_no):
    Exam_object=Exam.objects.get(name=exam_name, year=year)
    Question=Exam_object.questions.all()
    question= Question[question_no]
    no = question_no + 1
    
    dic= {
      
      "year": year,
      "name": exam_name,
      "body": question.body,
      "answer":question.answer,
      "options":question.options.all(),
      "correct_options":question.correct_options.all(),
      "subject":question.subject,
      "level":question.difficulty_level,
      "no":no

    }
    

    return render(request, "main/exam.html", dic)


def notes(request, subject):
  if subject=="Physics":
    return render(request, "main/notes/Physics/index.html")
  
  if subject=="Chemistry":
    return render(request, "main/notes/Chemistry/index.html")
  
  if subject=="Maths":
    return render(request, "main/notes/Maths/index.html")
  
def notes_details(request, subject, topic, chapter):
   user_profile= UserProfile.objects.get(user=request.user)
   if user_profile.is_subscriber:
      timezone= user_profile.subscription_end_date.tzinfo
   if user_profile.is_subscriber and user_profile.subscription_end_date > datetime.now(timezone):
    chapter = chapter.lower().replace(" ", "_") + ".html"
    return render(request, f"main/notes/{subject}/Chapters/{topic}/{chapter}")
   else:
        return HttpResponseRedirect(reverse('join'))

def wrules(request, subject):
  if subject=="Physics":
    return render(request, "main/working_rules/Physics/index.html")
  
  if subject=="Chemistry":
    return render(request, "main/working_rules/Chemistry/index.html")
  
  if subject=="Maths":
    return render(request, "main/working_rules/Maths/index.html")
  
def wrules_details(request, subject, topic, chapter):
   user_profile= UserProfile.objects.get(user=request.user)
   if user_profile.is_subscriber:
      timezone= user_profile.subscription_end_date.tzinfo
   if user_profile.is_subscriber and user_profile.subscription_end_date > datetime.now(timezone):
    chapter = chapter.lower().replace(" ", "_") + ".html"
    return render(request, f"main/working_rules/{subject}/Chapters/{topic}/{chapter}")
   else:
        return HttpResponseRedirect(reverse('join'))
   
@login_required
def generate_test(request, subject):
    user_profile = UserProfile.objects.get(user=request.user)
    if user_profile.is_subscriber:
      timezone= user_profile.subscription_end_date.tzinfo

    if user_profile.is_subscriber and user_profile.subscription_end_date > datetime.now(timezone):
    
      if subject not in ['physics', 'chemistry', 'math']:
        return HttpResponse("Invalid subject")

    # Get all available question IDs for the chosen subject
      all_question_ids = ExamQuestion.objects.filter(subject=subject).values_list('id', flat=True)
      

    # Randomly select 90 question IDs for the test
      selected_question_ids = sample(list(all_question_ids), 10)
      print(selected_question_ids)

    # Redirect to the test page with the selected question IDs in the URL
      return HttpResponseRedirect(reverse('main:test_page', args=[subject, ",".join(map(str, selected_question_ids))]))
    else:
       return HttpResponseRedirect(reverse('join'))

def test_page(request, subject, question_ids):
    # Split the question_ids string into a list of integers
    question_ids = [int(id) for id in question_ids.split(',')]
    questions = ExamQuestion.objects.filter(id__in=question_ids)
    
    context = {
        'subject': subject,
        'question_ids': question_ids,
        'questions': questions,
    }

    return render(request, 'main/test.html', context)

def submit_test(request):
    if request.method == 'POST':
        question_ids = request.GET.get('question_ids', '')
        question_ids = [int(id) for id in question_ids.split(',')]
        # Get the submitted data from the form
        submitted_answers = {}
        for key, value in request.POST.items():
            if key.startswith('question_'):
                question_id = int(key.split('_')[1])
                submitted_answers[question_id] = int(value)

        # Now you have a dictionary with question IDs as keys and selected answer option IDs as values.
        # You can perform grading logic here.
        total_questions = 10
        print(total_questions)
        correct_answers = 0

        for question_id, selected_option_id in submitted_answers.items():
            question = ExamQuestion.objects.get(id=question_id)
            correct_option_ids = [option.id for option in question.correct_options.all()]

            if selected_option_id in correct_option_ids:
                correct_answers += 1

        # Calculate the user's score
        score = (correct_answers / total_questions) * 100

        fireworks = False
        emoji = None

        if score >= 90:
            fireworks = True
            emoji = "🎉"  # Fireworks emoji
        elif score <= 50:
            emoji = "😞"  # Sad emoji
        elif score >= 75:
            emoji = "😃"  # Happy emoji

        context = {
            'score': score,
            'fireworks': fireworks,
            'emoji': emoji,
            'question_ids': question_ids,
        }

        # You can store the test results, e.g., in a UserTestResult model if needed.

        # Display a message with the user's score
        messages.success(request, f'Your score: {score:.2f}%')


    # Redirect the user to a relevant page after submitting the test.
    return render(request,"main/result.html", context)  # Change 'home' to the URL where you want to redirect the user.




def review_test(request):
    question_ids = request.GET.get('question_ids', '').split(',')
    question_ids = [int(id) for id in question_ids]

    # Get the questions for the chosen subject along with their correct answers
    questions = ExamQuestion.objects.filter(id__in=question_ids)

    context = {
        'questions': questions,
    }

    return render(request, 'main/review_test.html', context)

@csrf_exempt
def feedback(request):
    if request.method == 'POST':
        print(request)
        try:
            json_string = request.body.decode('utf-8')
          # Decode to string
            data = json.loads(json_string)
             # Parse JSON string
            # Access and use the data:
            if 'feedback' in data:
              print(data)
              print(f"feedback {data.get('feedback')}")
              answer_obj = BookQuestionFeedback(
                    book=data.get('book'),
                    chapter=data.get('chapter'),
                    exercise=data.get('exercise'),
                    no=data.get('no'),
                    feedback=data.get('feedback'),  # Assign answer text
                )
              answer_obj.save()

            else:
              print(data)
              print(f"answer {data.get('answer')}")
              answer_obj = UserSubmittedBookAnswer(
                    book=data.get('book'),
                    chapter=data.get('chapter'),
                    exercise=data.get('exercise'),

templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
    <script type="text/javascript" async
        src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML">
        </script>
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
          tex2jax: {
            inlineMath: [ ['$','$'], ["\\(","\\)"] ],
            processEscapes: true
          }
        });
      </script>
    <style>
        @media (max-width: 576px) {
            .dropdown-item::before {
                transform: rotate(-90deg);
            }
        }

        #math {
            margin-bottom: 60px;
        }

        body {
            background-image: url(/static/main/images/darkened.png);
            background-attachment: fixed;
            background-position: center;
            background-size: cover;
        }
    </style>
    {% block extrahead %}
    {% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Exammania</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile' %}">Your Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:index' %}">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-auto-close="outside" href="#" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Exams
                        </a>
                        <ul class="dropdown-menu">
                            <li class="dropstart"><a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown"
                                    href="#">Jee Mains</a>
                                <ul class="dropdown-menu" style="max-height: 200px; overflow-y: scroll;">
                                    <li><a href="{% url 'main:exam_solution' 'jee_mains' 2019 0 %}"
                                            class="dropdown-item">Jee Mains 2019</a></li>
                                    <li><a href="{% url 'main:exam_solution' 'jee_mains' 2013 0 %}"
                                            class="dropdown-item">Jee Mains 2013</a></li>
                                    <li><a href="{% url 'main:exam_solution' 'jee_mains' 2019 0 %}"
                                            class="dropdown-item">Jee Mains 2006</a></li>
                                    <li><a href="{% url 'main:exam_solution' 'jee_mains' 2019 0 %}"
                                            class="dropdown-item">Jee Mains 2007</a></li>
                                    <li><a href="{% url 'main:exam_solution' 'jee_mains' 2019 0 %}"
                                            class="dropdown-item">Jee Mains 2008</a></li>
                                    <li><a href="{% url 'main:exam_solution' 'jee_mains' 2019 0 %}"
                                            class="dropdown-item">Jee Mains 2009</a></li>
                                </ul>
                            </li>
                            <li class="dropstart"><a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown"
                                    href="#">Jee Advanced</a>
                                <ul class="dropdown-menu" style="max-height: 200px; overflow-y: scroll;">
                                    <li><a href="{% url 'main:exam_solution' 'jee_mains' 2019 0 %}"
                                            class="dropdown-item">Jee Advanced 2004</a></li>
                                    <li><a href="{% url 'main:exam_solution' 'jee_mains' 2019 0 %}"
                                            class="dropdown-item">Jee Advanced 2005</a></li>
                                    <li><a href="{% url 'main:exam_solution' 'jee_mains' 2019 0 %}"
                                            class="dropdown-item">Jee Advanced 2006</a></li>
                                    <li><a href="{% url 'main:exam_solution' 'jee_mains' 2019 0 %}"
                                            class="dropdown-item">Jee Advanced 2007</a></li>
                                    <li><a href="{% url 'main:exam_solution' 'jee_mains' 2019 0 %}"
                                            class="dropdown-item">Jee Advanced 2008</a></li>
                                    <li><a href="{% url 'main:exam_solution' 'jee_mains' 2019 0 %}"
                                            class="dropdown-item">Jee Advanced 2009</a></li>
                                    <li><a href="{% url 'main:exam_solution' 'jee_mains' 2019 0 %}"
                                            class="dropdown-item">Jee Advanced 2010</a></li>
                                    <li><a href="{% url 'main:exam_solution' 'jee_mains' 2019 0 %}"
                                            class="dropdown-item">Jee Advanced 2011</a></li>
                                    <li><a href="{% url 'main:exam_solution' 'jee_mains' 2019 0 %}"
                                            class="dropdown-item">Jee Advanced 2012</a></li>
                                </ul>
                            </li>

                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:book_solution' %}">Book Solutions</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="subjectDropdown" role="button"
                            data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Notes
                        </a>
                        <div class="dropdown-menu" aria-labelledby="subjectDropdown">
                            <a class="dropdown-item" href="{% url 'main:notes' 'Physics' %}">Physics Notes</a>
                            <a class="dropdown-item" href="{% url 'main:notes' 'Chemistry' %}">Chemistry Notes</a>
                            <a class="dropdown-item" href="{% url 'main:notes' 'Maths' %}">Maths Notes</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'videos_main' %}">Videos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'question_list' %}">Ask</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'join' %}">Subscribe</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="subjectDropdown" role="button"
                            data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Test
                        </a>
                        <div class="dropdown-menu" aria-labelledby="subjectDropdown">
                            <a class="dropdown-item" href="{% url 'main:generate_test' 'physics' %}">Physics</a>
                            <a class="dropdown-item" href="{% url 'main:generate_test' 'chemistry' %}">Chemistry</a>
                            <a class="dropdown-item" href="{% url 'main:generate_test' 'math' %}">Math</a>
                        </div>
                    </li>
                    {% block extranav %}
                    {% endblock %}
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}

                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    <p class="mb-5" style="text-align: center;">[mathjax]</p>
    {% block body %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    {% block script%}
    {% endblock %}
</body>

</html>

templates/main/chapterlist.html
{% extends 'main/base.html' %}
{% load static %}
{% block extrahead %}


<link rel="stylesheet" href="{% static 'main/css/chapterlist.css' %}">
{% endblock %}

{% block body %}
<div class="container">
  <h1 id="heading">{{ book.name }}</h1>
  {% for chapter in Chapters %}
  <h4 id="chapter_name">{{ forloop.counter }}.&nbsp;&nbsp;<a
      href="{% url 'main:exercise_list' book.name chapter.name %}">
      {{ chapter.name }}</a></h4>
  {% endfor %}
  {% endblock %}


</div>

{% block script%}
{% endblock %}

templates/main/exerciselist.html
{% extends 'main/base.html' %}

{% load static %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'main/css/exerciselist.css' %}">
{% endblock %}

{% block body %}
<div class="container">
    <h1 id="heading">{{ Chapter.name }}</h1>
    {% for exercise in Exercises %}
    <p id="exercise_name">{{ forloop.counter }}.&nbsp;&nbsp;Exercise&nbsp;&nbsp;<a
            href="{% url 'main:exercise_solution' Book.name Chapter.name exercise.name 0 %}">{{ exercise.name }}</a>

    </p>
    {% endfor %}
</div>
{% endblock %}
</div>

{% block script %}
{# Add your JavaScript code here if needed #}
{% endblock %}

templates/main/result.html
{% extends 'main/base.html' %}
{% load static %}
{% block extrahead %}
<link rel="stylesheet" href="{% static 'main/css/animate.css' %}">
{% endblock %}
{% block body %}


<h1>{{ subject }} Test Result</h1>

{% if fireworks %}
<div id="fireworks-container">
    <div class="fireworks"></div>
    <!-- Add more fireworks elements as needed -->
</div>
{% endif %}

<div id="emoji" style="font-size: 100px;">{{ emoji }}</div>

<h2>Your Score: {{ score }}%</h2>

<audio id="fireworks-sound" src="{% static 'main/audio/fireworks2.mp3' %}" preload="auto"></audio>
<p style="text-align: center; margin-top: 20px;"><a href="{% url 'main:generate_test' 'physics' %}"
        style="text-decoration: none; color:black; font-size: 20px; border:1px solid black; border-radius: 10px; background-color: orange; padding: 5px;">Take
        test again</a></p>
<p style="text-align: center; margin-top: 20px;">
    <a href="{% url 'main:review_test' %}?question_ids={{ question_ids|join:',' }}"
        style="text-decoration: none; color:black; font-size: 20px; border:1px solid black; border-radius: 10px; background-color: orange; padding: 5px;">
        Review Test
    </a>
</p>
{% endblock %}
{% block script %}
<script>

    // JavaScript to trigger fireworks animation and sound
    {% if fireworks %}
    window.addEventListener('load', function () {
        const firework = document.querySelectorAll('.fireworks');
        firework.forEach(function (firework, index) {
            setTimeout(function () {
                firework.style.top = Math.random() * 100 + 'vh';
                firework.style.left = Math.random() * 100 + 'vw';
                playFireworksSound();
            }, index * 100);
        });
    });

    function playFireworksSound() {
        const audio = document.getElementById('fireworks-sound');
        audio.play();
    }
    {% endif %}
</script>
{% endblock %}

templates/main/review_test.html
{% extends 'main/base.html' %}
{% block body %}
<h1>{{ subject }} Test Review</h1>

<ul>
    {% for question in questions %}
    <li>
        <strong>Question:</strong> {{ question.body }}<br>

        <strong>Correct Answer:</strong> {{ question.answer }}
    </li>
    {% endfor %}
</ul>

<p>
    <a href="{% url 'main:generate_test' 'physics' %}" class="btn btn-primary">Take Another Test</a>
</p>
{% endblock %}